# Generated by Django 5.0.1 on 2026-02-02 07:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Доставка без задержек', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(default='Привезём букет в течение 90 минут по городу или ко времени мероприятия.', verbose_name='Подзаголовок')),
                ('benefit_1', models.CharField(default='Бесплатная доставка от 5 000 ₽', max_length=200, verbose_name='Преимущество 1')),
                ('benefit_2', models.CharField(default='Фото готового букета в мессенджер', max_length=200, verbose_name='Преимущество 2')),
                ('benefit_3', models.CharField(default='Аккуратная упаковка и фирменная открытка', max_length=200, verbose_name='Преимущество 3')),
                ('step_1', models.CharField(default='Вы выбираете букет или собираете свой.', max_length=200, verbose_name='Шаг 1')),
                ('step_2', models.CharField(default='Оставляете контакты и адрес.', max_length=200, verbose_name='Шаг 2')),
                ('step_3', models.CharField(default='Мы собираем и отправляем курьера.', max_length=200, verbose_name='Шаг 3')),
            ],
            options={
                'verbose_name': 'Информация о доставке',
                'verbose_name_plural': 'Информация о доставке',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Доставка за 90 минут', max_length=100, verbose_name='Метка')),
                ('title', models.CharField(default='Живые эмоции в каждом букете', max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(default='Выбрать букет', max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='#catalog', max_length=200, verbose_name='Ссылка кнопки')),
                ('secondary_button_text', models.CharField(default='Собрать свой', max_length=100, verbose_name='Текст второй кнопки')),
                ('secondary_button_link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка второй кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Изображение')),
                ('badge_number', models.CharField(default='850+', max_length=50, verbose_name='Число в бейдже')),
                ('badge_text', models.CharField(default='довольных клиентов', max_length=100, verbose_name='Текст бейджа')),
                ('benefit_1', models.CharField(default='Фото букета перед отправкой', max_length=200, verbose_name='Преимущество 1')),
                ('benefit_2', models.CharField(default='Оплата онлайн и при получении', max_length=200, verbose_name='Преимущество 2')),
                ('benefit_3', models.CharField(default='Работаем 24/7', max_length=200, verbose_name='Преимущество 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Hero секция',
                'verbose_name_plural': 'Hero секция',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram ID пользователя')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('delivering', 'Доставляется'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Скидка %')),
                ('has_subscription', models.BooleanField(default=False, verbose_name='Есть подписка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎁', max_length=10, verbose_name='Иконка (emoji)')),
                ('title', models.CharField(default='Скидка 10% за подписку!', max_length=200, verbose_name='Заголовок')),
                ('text', models.CharField(default='Подпишитесь на нашу группу через бота и получите скидку на первый заказ', max_length=300, verbose_name='Текст')),
                ('button_text', models.CharField(default='Подписаться', max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промо баннер',
                'verbose_name_plural': 'Промо баннер',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Цветочная Лавка', max_length=200, verbose_name='Название сайта')),
                ('phone', models.CharField(default='+7 (999) 123-45-67', max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('telegram_bot_link', models.URLField(blank=True, verbose_name='Ссылка на Telegram бота')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('vk_link', models.URLField(blank=True, verbose_name='VKontakte')),
                ('telegram_channel_link', models.URLField(blank=True, verbose_name='Telegram канал')),
                ('footer_text', models.CharField(default='Сделано с любовью к цветам', max_length=300, verbose_name='Текст в подвале')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', '-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(5, '5 - Отлично'), (4, '4 - Хорошо'), (3, '3 - Нормально'), (2, '2 - Плохо'), (1, '1 - Очень плохо')], default=5, verbose_name='Оценка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
