# Generated by Django 5.0.1 on 2026-02-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_price',
            field=models.BooleanField(default=False, help_text='Если галочка стоит, цена не будет отображаться на сайте', verbose_name='Скрыть цену'),
        ),
    ]
