# Generated by Django 5.0.1 on 2026-02-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_hide_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(default='catalog.html', max_length=200, verbose_name='Ссылка кнопки'),
        ),
    ]
