# Generated by Django 5.0.1 on 2026-02-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_herosection_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Телефон (нормализованный)'),
        ),
    ]
