# Generated by Django 5.0.1 on 2026-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_phone_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='review',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID пользователя'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_link',
            field=models.URLField(blank=True, default='https://t.me/testikbotick_bot', verbose_name='Ссылка на Telegram бота'),
        ),
    ]
