# Generated by Django 5.0.1 on 2026-02-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_review_avatar_review_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/ready/', verbose_name='Фото готового букета'),
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Без @', max_length=100, verbose_name='Telegram username')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Админ бота',
                'verbose_name_plural': 'Админы бота',
                'indexes': [models.Index(fields=['is_active', 'telegram_user_id'], name='catalog_bot_is_acti_87d010_idx'), models.Index(fields=['is_active', 'username'], name='catalog_bot_is_acti_8de80d_idx')],
            },
        ),
    ]
